var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,h="undefined"!=typeof WorkerGlobalScope,m="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,ba=Object.assign({},f),r="./this.program",ca=(a,b)=>{throw b;},t="",da,u;
if(m){var fs=require("fs");require("path");t=__dirname+"/";u=a=>{a=v(a)?new URL(a):a;return fs.readFileSync(a)};da=async a=>{a=v(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!f.thisProgram&&1<process.argv.length&&(r=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ca=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||h)h?t=self.location.href:"undefined"!=typeof document&&document.currentScript&&(t=document.currentScript.src),t=t.startsWith("blob:")?
"":t.slice(0,t.replace(/[?#].*/,"").lastIndexOf("/")+1),h&&(u=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),da=async a=>{if(v(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var ea=f.print||console.log.bind(console),x=f.printErr||console.error.bind(console);Object.assign(f,ba);ba=null;f.thisProgram&&(r=f.thisProgram);var y=f.wasmBinary,fa,ha=!1,z,C,ia,D,E,ja,v=a=>a.startsWith("file://"),G=0,H=null;function I(a){f.onAbort?.(a);a="Aborted("+a+")";x(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ka;
async function la(a){if(!y)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==ka&&y)a=new Uint8Array(y);else if(u)a=u(a);else throw"both async and sync fetching of the wasm failed";return a}async function ma(a,b){try{var c=await la(a);return await WebAssembly.instantiate(c,b)}catch(d){x(`failed to asynchronously prepare wasm: ${d}`),I(d)}}
async function na(a){var b=ka;if(!y&&"function"==typeof WebAssembly.instantiateStreaming&&!v(b)&&!m)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){x(`wasm streaming compile failed: ${d}`),x("falling back to ArrayBuffer instantiation")}return ma(b,a)}
var ta={31276:(a,b,c)=>{var d=require("ws"),e=require("http");const g=require("fs");e=e.createServer(function(n,p){let k="text/html",q="index.html";switch(n.url){case "/":break;case "/gardn-client.js":k="application/javascript";q="gardn-client.js";break;case "/gardn-client.wasm":k="application/wasm";q="gardn-client.wasm";break;default:q=""}g.existsSync(q)?(p.writeHead(200,{"Content-Type":k}),p.end(g.readFileSync(q))):(p.writeHead(404,{"Content-Type":k}),p.end())});e.listen(a,function(){console.log("Server running at http://localhost:"+
a)});d=new d.Server({server:e});f.K={};let l=0;d.on("connection",function(n){const p=l;f.K[p]=n;oa(p);l=l+1|0;n.on("message",function(k){k=new Uint8Array(k);const q=k.length>c?c:k.length;k=k.subarray(0,q);C.set(k,b);pa(p,q)});n.on("close",function(k){ra(p,k);delete f.K[p]})})},32555:a=>{setInterval(sa,a)},32583:(a,b,c)=>{f.K&&f.K[a]&&f.K[a].send(C.subarray(b,b+c))},32727:a=>{f.K&&f.K[a]&&f.K[a].close()}};
class ua{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var va=a=>{for(;0<a.length;)a.shift()(f)},wa=[],xa=[],ya=()=>{var a=f.preRun.shift();xa.unshift(a)},za=f.noExitRuntime||!0,Aa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,J=(a,b=0)=>{for(var c=b+NaN,d=b;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&Aa)return Aa.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|g);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|l:(e&7)<<18|g<<12|l<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):
(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c};class Ba{constructor(a){this.S=a-24}}
var Ca=0,Da=0,K=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var l=a.charCodeAt(g);if(55296<=l&&57343>=l){var n=a.charCodeAt(++g);l=65536+((l&1023)<<10)|n&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e},Ea=[],Fa={},Ha=()=>{if(!Ga){var a={USER:"web_user",LOGNAME:"web_user",
PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:r||"./this.program"},b;for(b in Fa)void 0===Fa[b]?delete a[b]:a[b]=Fa[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Ga=c}return Ga},Ga,Ia=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ja=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);
(a=Ia(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ka=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},La=()=>{if(m){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Ma=a=>{(Ma=La())(a)},Na=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ia(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Oa=[],Pa=[];function Qa(a,b){Pa[a]={input:[],output:[],M:b};Ra(a,Sa)}
var Sa={open(a){var b=Pa[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close(a){a.tty.M.fsync(a.tty)},fsync(a){a.tty.M.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.M.$)throw new L(60);for(var e=0,g=0;g<d;g++){try{var l=a.tty.M.$(a.tty)}catch(n){throw new L(29);}if(void 0===l&&0===e)throw new L(6);if(null===l||void 0===l)break;e++;b[c+g]=l}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.M.W)throw new L(60);try{for(var e=0;e<d;e++)a.tty.M.W(a.tty,b[c+e])}catch(g){throw new L(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},Ta={$(){a:{if(!Oa.length){var a=null;if(m){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}for(c=b=0;c<a.length;++c)d=a.charCodeAt(c),127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,
++c):b+=3;b=Array(b+1);a=K(a,b,0,b.length);b.length=a;Oa=b}a=Oa.shift()}return a},W(a,b){null===b||10===b?(ea(J(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ea(J(a.output)),a.output=[])},qa(){return{la:25856,na:5,ka:191,ma:35387,ja:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},ra(){return 0},sa(){return[24,80]}},Ua={W(a,b){null===b||10===b?(x(J(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(x(J(a.output)),
a.output=[])}};function Va(a,b){var c=a.A?a.A.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.A,a.A=new Uint8Array(b),0<a.D&&a.A.set(c.subarray(0,a.D),0))}
var M={G:null,I(){return M.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.G||(M.G={dir:{node:{J:M.B.J,H:M.B.H,lookup:M.B.lookup,P:M.B.P,rename:M.B.rename,unlink:M.B.unlink,rmdir:M.B.rmdir,readdir:M.B.readdir,symlink:M.B.symlink},stream:{F:M.C.F}},file:{node:{J:M.B.J,H:M.B.H},stream:{F:M.C.F,read:M.C.read,write:M.C.write,X:M.C.X,ba:M.C.ba,ea:M.C.ea}},link:{node:{J:M.B.J,H:M.B.H,readlink:M.B.readlink},stream:{}},Y:{node:{J:M.B.J,H:M.B.H},stream:Wa}});
c=Xa(a,b,c,d);16384===(c.mode&61440)?(c.B=M.G.dir.node,c.C=M.G.dir.stream,c.A={}):32768===(c.mode&61440)?(c.B=M.G.file.node,c.C=M.G.file.stream,c.D=0,c.A=null):40960===(c.mode&61440)?(c.B=M.G.link.node,c.C=M.G.link.stream):8192===(c.mode&61440)&&(c.B=M.G.Y.node,c.C=M.G.Y.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.A[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},pa(a){return a.A?a.A.subarray?a.A.subarray(0,a.D):new Uint8Array(a.A):new Uint8Array(0)},B:{J(a){var b={};b.dev=8192===(a.mode&61440)?
a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.D:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},H(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.D!=b&&(0==b?(a.A=null,a.D=0):(c=a.A,a.A=new Uint8Array(b),c&&a.A.set(c.subarray(0,
Math.min(b,a.D))),a.D=b)))},lookup(){throw M.Z;},P(a,b,c,d){return M.createNode(a,b,c,d)},rename(a,b,c){try{var d=O(b,c)}catch(g){}if(d){if(16384===(a.mode&61440))for(var e in d.A)throw new L(55);e=Za(d.parent.id,d.name);if(P[e]===d)P[e]=d.L;else for(e=P[e];e;){if(e.L===d){e.L=d.L;break}e=e.L}}delete a.parent.A[a.name];b.A[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.A[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=O(a,b),d;for(d in c.A)throw new L(55);
delete a.A[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.A)]},symlink(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new L(28);return a.link}},C:{read(a,b,c,d,e){var g=a.node.A;if(e>=a.node.D)return 0;a=Math.min(a.node.D-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.A||a.A.subarray)){if(g)return a.A=
b.subarray(c,c+d),a.D=d;if(0===a.D&&0===e)return a.A=b.slice(c,c+d),a.D=d;if(e+d<=a.D)return a.A.set(b.subarray(c,c+d),e),d}Va(a,e+d);if(a.A.subarray&&b.subarray)a.A.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.A[e+g]=b[c+g];a.D=Math.max(a.D,e+d);return d},F(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.D);if(0>b)throw new L(28);return b},X(a,b,c){Va(a.node,b+c);a.node.D=Math.max(a.node.D,b+c)},ba(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.A;
if(e&2||!a||a.buffer!==z.buffer){d=!0;I();e=void 0;if(!e)throw new L(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=!1,e=a.byteOffset;return{S:e,ia:d}},ea(a,b,c,d){M.C.write(a,b,0,d,c,!1);return 0}}},$a=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},ab=null,bb={},Q=[],cb=1,P=null,db=!1,eb=!0,fb={},L=class{name="ErrnoError";constructor(a){this.N=a}},gb=class{O={};node=null;get flags(){return this.O.flags}set flags(a){this.O.flags=
a}get position(){return this.O.position}set position(a){this.O.position=a}},hb=class{B={};C={};R=null;constructor(a,b,c,d){a||=this;this.parent=a;this.I=a.I;this.id=cb++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function R(a,b={}){if(!a)throw new L(44);b.U??(b.U=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=ab,e="/",g=0;g<a.length;g++){var l=g===a.length-1;if(l&&b.parent)break;if("."!==a[g])if(".."===a[g])e=Ka(e),d=d.parent;else{e=Ja(e+"/"+a[g]);try{d=O(d,a[g])}catch(n){if(44===n?.N&&l&&b.ga)return{path:e};throw n;}!d.R||l&&!b.U||(d=d.R.root);if(40960===(d.mode&61440)&&(!l||b.T)){if(!d.B.readlink)throw new L(52);d=d.B.readlink(d);"/"===d.charAt(0)||(d=
Ka(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new L(32);}function Za(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%P.length}function O(a,b){var c=16384===(a.mode&61440)?(c=S(a,"x"))?c:a.B.lookup?0:2:54;if(c)throw new L(c);for(c=P[Za(a.id,b)];c;c=c.L){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.B.lookup(a,b)}function Xa(a,b,c,d){a=new hb(a,b,c,d);b=Za(a.parent.id,a.name);a.L=P[b];return P[b]=a}
function ib(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function S(a,b){if(eb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function jb(a,b){if(16384!==(a.mode&61440))return 54;try{return O(a,b),20}catch(c){}return S(a,"wx")}function T(a){a=Q[a];if(!a)throw new L(8);return a}function kb(a,b){var c=null?.C.H,d=c?null:a;c??=a.B.H;if(!c)throw new L(63);c(d,b)}
var Wa={open(a){a.C=bb[a.node.rdev].C;a.C.open?.(a)},F(){throw new L(70);}};function Ra(a,b){bb[a]={C:b}}function lb(a,b){var c="/"===b;if(c&&ab)throw new L(10);if(!c&&b){var d=R(b,{U:!1});b=d.path;d=d.node;if(d.R)throw new L(10);if(16384!==(d.mode&61440))throw new L(54);}b={type:a,ta:{},da:b,fa:[]};a=a.I(b);a.I=b;b.root=a;c?ab=a:d&&(d.R=b,d.I&&d.I.fa.push(b))}
function mb(a,b,c){var d=R(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new L(28);if("."===a||".."===a)throw new L(20);var e=jb(d,a);if(e)throw new L(e);if(!d.B.P)throw new L(63);return d.B.P(d,a,b,c)}function U(a){return mb(a,16895,0)}function V(a,b,c){"undefined"==typeof c&&(c=b,b=438);mb(a,b|8192,c)}
function nb(a,b){if(!Na(a))throw new L(44);var c=R(b,{parent:!0}).node;if(!c)throw new L(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=jb(c,b);if(d)throw new L(d);if(!c.B.symlink)throw new L(63);c.B.symlink(c,b,a)}
function ob(a,b){if(""===a)throw new L(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");a=R(a,{T:!(b&131072),ga:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new L(20);}else{if(e)throw new L(31);d=mb(a,c|511,0);g=!0}if(!d)throw new L(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new L(54);
if(!g&&(e=d?40960===(d.mode&61440)?32:16384===(d.mode&61440)&&("r"!==ib(b)||b&576)?31:S(d,ib(b)):44))throw new L(e);if(b&512&&!g){e=d;e="string"==typeof e?R(e,{T:!0}).node:e;if(16384===(e.mode&61440))throw new L(31);if(32768!==(e.mode&61440))throw new L(28);var l=S(e,"w");if(l)throw new L(l);kb(e,{size:0,timestamp:Date.now()})}b&=-131713;a:for(e=d;;){if(e===e.parent){e=e.I.da;var n=n?"/"!==e[e.length-1]?`${e}/${n}`:e+n:e;break a}n=n?`${e.name}/${n}`:e.name;e=e.parent}n={node:d,path:n,flags:b,seekable:!0,
position:0,C:d.C,ha:[],error:!1};e=-1;n=Object.assign(new gb,n);if(-1==e)a:{for(e=0;4096>=e;e++)if(!Q[e])break a;throw new L(33);}n.fd=e;Q[e]=n;n.C.open&&n.C.open(n);g&&(c&=511,d="string"==typeof d?R(d,{T:!0}).node:d,kb(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),oa:void 0}));!f.logReadFiles||b&1||a in fb||(fb[a]=1)}function pb(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.C.F)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.C.F(a,b,c);a.ha=[]}
function W(a,b,c){a=Ja("/dev/"+a);var d=$a(!!b,!!c);W.aa??(W.aa=64);var e=W.aa++<<8|0;Ra(e,{open(g){g.seekable=!1},close(){c?.buffer?.length&&c(10)},read(g,l,n,p){for(var k=0,q=0;q<p;q++){try{var w=b()}catch(A){throw new L(29);}if(void 0===w&&0===k)throw new L(6);if(null===w||void 0===w)break;k++;l[n+q]=w}k&&(g.node.atime=Date.now());return k},write(g,l,n,p){for(var k=0;k<p;k++)try{c(l[n+k])}catch(q){throw new L(29);}p&&(g.node.mtime=g.node.ctime=Date.now());return k}});V(a,d,e)}var Y={};P=Array(4096);
lb(M,"/");U("/tmp");U("/home");U("/home/web_user");(function(){U("/dev");Ra(259,{read:()=>0,write:(d,e,g,l)=>l,F:()=>0});V("/dev/null",259);Qa(1280,Ta);Qa(1536,Ua);V("/dev/tty",1280);V("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ma(a),b=a.byteLength);return a[--b]};W("random",c);W("urandom",c);U("/dev/shm");U("/dev/shm/tmp")})();
(function(){U("/proc");var a=U("/proc/self");U("/proc/self/fd");lb({I(){var b=Xa(a,"fd",16895,73);b.C={F:M.C.F};b.B={lookup(c,d){c=+d;var e=T(c);c={parent:null,I:{da:"fake"},B:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(Q.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();M.Z=new L(44);M.Z.stack="<generic error, no stack>";
var qb={d:(a,b,c,d)=>I(`Assertion failed: ${a?J(C,a):""}, at: `+[b?b?J(C,b):"":"unknown filename",c,d?d?J(C,d):"":"unknown function"]),b:(a,b,c)=>{var d=new Ba(a);D[d.S+16>>2]=0;D[d.S+4>>2]=b;D[d.S+8>>2]=c;Ca=a;Da++;throw Ca;},n:()=>I(""),k:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();D[a>>2]=60*Math.max(g,e);ia[b>>2]=Number(g!=e);b=l=>{var n=Math.abs(l);return`UTC${0<=l?"-":"+"}${String(Math.floor(n/60)).padStart(2,"0")}${String(n%
60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(K(a,C,c,17),K(b,C,d,17)):(K(a,C,d,17),K(b,C,c,17))},i:function(a,b,c){if(!(0<=a&&3>=a))return 28;E[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},a:(a,b,c)=>{Ea.length=0;for(var d;d=C[b++];){var e=105!=d;e&=112!=d;c+=e&&c%8?4:0;Ea.push(112==d?D[c>>2]:106==d?E[c>>3]:105==d?ia[c>>2]:ja[c>>3]);c+=e?8:4}return ta[a](...Ea)},j:()=>Date.now(),h:()=>{I("OOM")},l:(a,b)=>{var c=0;Ha().forEach((d,e)=>{var g=b+c;e=D[a+4*e>>2]=g;for(g=0;g<
d.length;++g)z[e++]=d.charCodeAt(g);z[e]=0;c+=d.length+1});return 0},m:(a,b)=>{var c=Ha();D[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);D[b>>2]=d;return 0},e:function(a){try{var b=T(a);if(null===b.fd)throw new L(8);b.V&&(b.V=null);try{b.C.close&&b.C.close(b)}catch(c){throw c;}finally{Q[b.fd]=null}b.fd=null;return 0}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return c.N}},f:function(a,b,c,d){try{a:{var e=T(a);a=b;for(var g,l=b=0;l<c;l++){var n=D[a>>2],p=D[a+4>>2];a+=8;var k=
e,q=g,w=z;if(0>p||0>q)throw new L(28);if(null===k.fd)throw new L(8);if(1===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);if(!k.C.read)throw new L(28);var A="undefined"!=typeof q;if(!A)q=k.position;else if(!k.seekable)throw new L(70);var X=k.C.read(k,w,n,p,q);A||(k.position+=X);var F=X;if(0>F){var N=-1;break a}b+=F;if(F<p)break;"undefined"!=typeof g&&(g+=F)}N=b}D[d>>2]=N;return 0}catch(B){if("undefined"==typeof Y||"ErrnoError"!==B.name)throw B;return B.N}},g:function(a,
b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=T(a);pb(e,b,c);E[d>>3]=BigInt(e.position);e.V&&0===b&&0===c&&(e.V=null);return 0}catch(g){if("undefined"==typeof Y||"ErrnoError"!==g.name)throw g;return g.N}},c:function(a,b,c,d){try{a:{var e=T(a);a=b;for(var g,l=b=0;l<c;l++){var n=D[a>>2],p=D[a+4>>2];a+=8;var k=e,q=n,w=p,A=g,X=z;if(0>w||0>A)throw new L(28);if(null===k.fd)throw new L(8);if(0===(k.flags&2097155))throw new L(8);if(16384===(k.node.mode&61440))throw new L(31);
if(!k.C.write)throw new L(28);k.seekable&&k.flags&1024&&pb(k,0,2);var F="undefined"!=typeof A;if(!F)A=k.position;else if(!k.seekable)throw new L(70);var N=k.C.write(k,X,q,w,A,void 0);F||(k.position+=N);var B=N;if(0>B){var Ya=-1;break a}b+=B;if(B<p)break;"undefined"!=typeof g&&(g+=B)}Ya=b}D[d>>2]=Ya;return 0}catch(qa){if("undefined"==typeof Y||"ErrnoError"!==qa.name)throw qa;return qa.N}}},Z;
(async function(){function a(c){Z=c.exports;fa=Z.o;c=fa.buffer;f.HEAP8=z=new Int8Array(c);f.HEAP16=new Int16Array(c);f.HEAPU8=C=new Uint8Array(c);f.HEAPU16=new Uint16Array(c);f.HEAP32=ia=new Int32Array(c);f.HEAPU32=D=new Uint32Array(c);f.HEAPF32=new Float32Array(c);f.HEAPF64=ja=new Float64Array(c);f.HEAP64=E=new BigInt64Array(c);f.HEAPU64=new BigUint64Array(c);G--;f.monitorRunDependencies?.(G);0==G&&H&&(c=H,H=null,c());return Z}G++;f.monitorRunDependencies?.(G);var b={a:qb};if(f.instantiateWasm)return new Promise(c=>
{f.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});ka??=f.locateFile?f.locateFile("gardn-server.wasm",t):t+"gardn-server.wasm";return a((await na(b)).instance)})();var rb=f._main=(a,b)=>(rb=f._main=Z.r)(a,b),oa=f._on_connect=a=>(oa=f._on_connect=Z.s)(a),ra=f._on_disconnect=(a,b)=>(ra=f._on_disconnect=Z.t)(a,b),sa=f._tick=()=>(sa=f._tick=Z.u)(),pa=f._on_message=(a,b)=>(pa=f._on_message=Z.v)(a,b);
function sb(){function a(){f.calledRun=!0;if(!ha){if(!f.noFSInit&&!db){var b,c;db=!0;d??=f.stdin;b??=f.stdout;c??=f.stderr;d?W("stdin",d):nb("/dev/tty","/dev/stdin");b?W("stdout",null,b):nb("/dev/tty","/dev/stdout");c?W("stderr",null,c):nb("/dev/tty1","/dev/stderr");ob("/dev/stdin",0);ob("/dev/stdout",1);ob("/dev/stderr",1)}Z.p();eb=!1;f.onRuntimeInitialized?.();if(!f.noInitialRun){var d=rb;try{var e=d(0,0);za||(f.onExit?.(e),ha=!0);ca(e,new ua(e))}catch(g){g instanceof ua||"unwind"==g||ca(1,g)}}if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)e=f.postRun.shift(),wa.unshift(e);va(wa)}}if(0<G)H=sb;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ya();va(xa);0<G?H=sb:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();sb();
